<?php
namespace App\Middleware;
// TODO: Archivo para añadir middleware a la aplicacion slim ...
// *: Importamos las classes necesarias ...
use Slim\App;
use Slim\Views\TwigMiddleware;
return function (App $app) {
    $container = $app->getContainer();
    $settings = $container->get('settings');
    $app->addErrorMiddleware(
        $settings['displayErrorDetails'],
        $settings['logErrorDetails'],
        $settings['logErrors']
    ); //?: Convierte la salida de errores ...
    // *: Añadir Twig-View Middleware ...
    $app->add(TwigMiddleware::create($app, $container->get('view')));
    // *: Middleware de Validaciones ...
    $app->add(new \App\Middleware\ValidationErrorsMiddleware($container)); // ?: Controlamos la salida de errores de la validacion ...
    // *: Middleware de Imputs ...
    $app->add(new \App\Middleware\OldinputMiddleware($container)); // ?: Controlamos el valor viejo del imput ...
    // *: Middleware de Csrf ...
    $app->add(new \App\Middleware\CsrfViewMiddleware($container)); // ?: Controlamos el token de los formularios ...
    // *: Añadir CSRF Middleware ...
    $app->add($container->get('csrf'));
    // $app->addRoutingMiddleware();
};
