<?php
// TODO: Archivo de rutas Slim ...
// *: Importamos las classes necesarias ...
use Slim\App;
use Psr\Http\Message\ResponseInterface as Response;
use Psr\Http\Message\ServerRequestInterface as Request;
// *: Creamos rutas ...
return function (App $app)
{
    // *: Rutas web ...
    $app->get('/', 'IndexController:index')->setName('welcom');

    $app->get('/home', 'HomeController:index')->setName('home');

    // *: Rutas Auth ...
    // *: Ruta del registro ...
    $app->get('/register', 'RegisterController:index')->setName('auth.register');
    $app->post('/register', 'RegisterController:register');
    // *: Ruta del login ...
    $app->get('/login', 'LoginController:index')->setName('auth.login');
    $app->post('/login', 'LoginController:login');
}; // ?: funcion de retorno y solicitud de la App ...